# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 17:14
from __future__ import unicode_literals

import app.keyvalue
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.TextField(blank=True, default='')),
                ('value2', app.keyvalue.KeyValueField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MySecondModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
            ],
        ),
    ]
